### ISSUE TITLE
AI SOV can't get enough pp to properly up its government stability

### ISSUE THREAD

**Issue by karrot1** [jespertjee/FR#102]
**Explanation of the issue:**
AI SOV can't get enough pp to up its government stability because it takes continuous focuses

**Screenshots / Video:**
![20190121151838_1](https://user-images.githubusercontent.com/6722625/51505626-b2f1fc00-1db5-11e9-88b1-cfd4b383a782.jpg)
![20190121151840_1](https://user-images.githubusercontent.com/6722625/51505627-b4232900-1db5-11e9-83d6-1b997c6bce13.jpg)

**Comment by fbruchmueller** [comment]
Fucking hell

**Comment by fbruchmueller** [comment]
fixed hopefully
