### ISSUE TITLE
Voroshilov's collecitivization can't continue

### ISSUE THREAD

**Issue by Sarah1917** [jespertjee/FR#109]
-->

Explanation of the issue: Being as inept as he was IRL Voroshilov is unable to continue his collectivization due to a lack of decisions (most likely being too busy LARPing as socialist Prussia)

Quick questions:

OS: Windows 7
HoI4 version: 1.5.4
Führerreich version: 0.2 beta
Using Steam? Yes
Were you in multiplayer? No 
List other mods used (including FR Music mod): FR Music Mod
Have you changed any files, outside of mods used? No 
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have?

**Steps to reproduce:**

1. Play Soviets 

2. Get Voroshilov

3. Start collectivization and pick all the decisions

4. No more decisions to gain more collectivization percentage

Other info: I'm at 1939 so maybe its just not their time to appear

**Possible cause:**

**Log file:**

**Screenshots / Video:**
 http://prntscr.com/mfquli

**Save game:**

**Comment by fbruchmueller** [comment]
more decisions should hopefully prevent this
