### ISSUE TITLE
Valkist Germany Event Bug (Germans leaving for Switzerland)

### ISSUE THREAD

**Issue by Capshades** [jespertjee/FR#111]
**Explanation of the issue:**
Germans leaving for Switzerland Event = should decrease the selected political group in germany, actually increases it.  For example, I selected "they can take the liberals" and it actually increased those party's influence in Germany, not decreased it.

OS:
HoI4 version: 1.5.4
Führerreich version: 0.2
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): None
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): -
Which DLC expansions do you NOT have? None, have all

**Comment by Drowse** [comment]
lol Swiss got scrapped rip
