### ISSUE TITLE
Flurry of unfired events at start of german campaign

### ISSUE THREAD

**Issue by Capshades** [jespertjee/FR#112]
**Explanation of the issue:**
At the start of the german campaign, have a whole flurry of messages pop up including "the pacific alliance" which is the US and Japan forming a faction, and "the US declares war on Japan," neither of which actually happens.

OS: Win10
HoI4 version: 1.5.4
Führerreich version: 0.2
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): None
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): -
Which DLC expansions do you NOT have? None, have all

**Comment by Drowse** [comment]
Added `is_triggered_only = yes` to those events
