### ISSUE TITLE
Missing loc keys in a Soviet event

### ISSUE THREAD

**Issue by Drozdovite** [jespertjee/FR#113]
**Explanation of the issue:**
Small issue found in my playthrough

**Quick questions:**

OS: Windows 8.1
HoI4 version:1.5.4
Führerreich version: 0.2.0
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): FR music mod, WW's map, WW's buttons, Quam's Graphics
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have?
None, I have all of them
**Steps to reproduce:**

1.Play the Game

2.Look around I guess.

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/40744314/52189023-d2a50d80-2814-11e9-9e5d-744a537ab7ce.png)

**Comment by fbruchmueller** [comment]
fixed
