### ISSUE TITLE
SOV Molotovs decision ''expansion of gulags'' does nothing

### ISSUE THREAD

**Issue by CzainjikMaster4444** [jespertjee/FR#116]
**Explanation of the issue:**
SOV ''expansion of gulags'' focus does nothing instead of adding 5% party popularity for NatCollectivists as it should.

**Quick questions:**

OS:
HoI4 version: 1.5.4
Führerreich version: 0.2
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): Coloured buttons, State transfer tool
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): 9552
Which DLC expansions do you NOT have? I have all of them 

**Steps to reproduce:**

1. Pick Molotov in SOV succesion event (idk what its called i played 0.2 only once)

2. Get Molotov as Chairman

3. Click ''expansion of gulags'' decision and see that it doesnt do anything

**Other info:**
This doesnt seem like anything for what a save game file needs to be added. Someone probably simply forgot to make the decision do anything.

**Possible cause:**
A dev made a slight mistake and forgot to put in code to add that 5% party pop.

**Comment by fbruchmueller** [comment]
should be fixed.
