### ISSUE TITLE
No descriptions for the Russian Republic 

### ISSUE THREAD

**Issue by GDSPathe** [jespertjee/FR#119]
**Explanation of the issue:**

None of the starter focuses have descriptions 

**Quick questions:**

OS: Windows 10
HoI4 version: 1.5.4
Führerreich version: 2.1
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): FR, FR Music Mod, Lamp's equipment icons 1-3, WW+ Buttons and Forestry, Gun Trucks, Unique Infantry equipment, More model images
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): 3899

Which DLC expansions do you NOT have? WtT

**Log file:**

[error.zip](https://github.com/Fuhrerreich/FR/files/2847530/error.zip)
[game.zip](https://github.com/Fuhrerreich/FR/files/2847531/game.zip)

**Screenshots / Video:**

https://steamuserimages-a.akamaihd.net/ugc/940592907855028842/322307C6CA6AAC53ACE3C0977809BEDA3C04F524/

**Save game:**

[RUS_1936_01_01_01.zip](https://github.com/Fuhrerreich/FR/files/2847532/RUS_1936_01_01_01.zip)

**Comment by Omanisch** [comment]
fixed
