### ISSUE TITLE
Hungarian Core on Central France

### ISSUE THREAD

**Issue by KSkwarczynski** [jespertjee/FR#120]
Explanation of the issue:  After Germany annexed Hungary and released Hungary via events Hungary gained core on Central France.

Quick questions:
OS: Win 10. 
HoI4 version:1.5.4.
Führerreich version: 0.2.1
Using Steam? Yes.
Were you in multiplayer? No.
List other mods used (including FR Music mod):  FR music, State transfer tool, More Division Icons, Coloured Airforce - Standard , Strategic View Adjustments , WW's Buttons+.
Have you changed any files, outside of mods used? No.
Checksum (four-letter code at the bottom of your title menu): 1503
Which DLC expansions do you NOT have?  I have all expansions.

Steps to reproduce:
1. Anex Hungary as Germany.
2. Relase puppet Hungary via event.
3. Look at region Centre in France.
Other info:

Possible cause:
Wrong province number in event

Screenshots / Video:
![bug](https://user-images.githubusercontent.com/45295406/52522622-01ddd380-2c88-11e9-968b-272646c40c3e.png)

**Comment by Drowse** [comment]
I believed I fix this a while ago. Think it was a state history file issue
