### ISSUE TITLE
German state with a confusing name

### ISSUE THREAD

**Issue by Liegnitz** [jespertjee/FR#121]
**Explanation of the issue:**

The state east of Berlin is called Kostschin, but kostschin is a small city in FR Poland.
Küstrin or Neumark are more appropriate 

**Quick questions:**

OS: 7 
HoI4 version: 1.5.4
Führerreich version: 0.2
Using Steam? y 
Were you in multiplayer? n 
List other mods used (including FR Music mod): n 
Have you changed any files, outside of mods used? n 
Which DLC expansions do you NOT have? MtG

**Comment by Drowse** [comment]
Updated the name to Neumark
