### ISSUE TITLE
Mitsubishi and Aichi isn't available as an air manufacturer 

### ISSUE THREAD

**Issue by TheTalkingKnot** [jespertjee/FR#122]
**Explanation of the issue:**
Mitsubishi and Aichi isn't available as an air manufacturer 

**Screenshots :**
![20190210123728_1](https://user-images.githubusercontent.com/47489264/52528366-28a41480-2d31-11e9-9fa4-1b17d7da012b.jpg)
![20190210121838_1](https://user-images.githubusercontent.com/47489264/52528367-2b9f0500-2d31-11e9-97f4-1452773117cc.jpg)

**Comment by Su1phur** [comment]
fixed
