### ISSUE TITLE
Kiev in state map, when it should be Kyiv

### ISSUE THREAD

**Issue by JonJon0428** [jespertjee/FR#124]
Fill in the placeholders below. Delete any headings and placeholders that you do not fill in.
PLEASE CHECK IF THIS ISSUE HAS BEEN REPORTED BEFORE!
Make sure your title explains the issue well.

Before you report a crash (CTD) issue, please ensure the following:
1. You were not running any other mods (FR music mod is fine, others not made by the FR team are not - yes, this includes graphical mods and things you believe are harmless). No, disabling the mods for a game where you've been running with them active previously doesn't count. If you want to report it anyhow, that's fine, but please be honest about their use and know that we might reject the report if you're using mods we're unfamiliar with.
2. That you have a save to include which crashes consistently (meaning: on each reload, within a reasonable time)
3. Make sure you include the game log, found in C:\Users\NAME\Documents\Paradox Interactive\Hearts of Iron IV\logs
4. That you have the checksum on hand - this is the four-letter code at the bottom of your title menu, and is vital for us to know if your files match ours.

Thanks for your patience! We'll do our best to address the isssue, if we can.

-->

**Explanation of the issue:**
The city of Kyiv is called Kiev on the state it inhabits 

**Quick questions:**

OS: Windows
HoI4 version: Newest 
Führerreich version: 0.2.1
Using Steam? YES 
Were you in multiplayer?
List other mods used (including FR Music mod): FR music
Have you changed any files, outside of mods used?
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have?

**Steps to reproduce:**

1. Look at the map

2.

**Other info:**

**Possible cause:**

**Log file:**

**Screenshots / Video:**

**Save game:**

**Comment by Drowse** [comment]
State name has been changed to Kyiv
