### ISSUE TITLE
Unrelated event when playing as Germany

### ISSUE THREAD

**Issue by KarellenSolaris** [jespertjee/FR#125]
**Explanation of the issue:**
As soon as I started a game as Germany I got this event, which I presume is not something Germany is supposed to get.

**Screenshots / Video:**
![20190210185553_1](https://user-images.githubusercontent.com/44334226/52550767-c9e6a580-2dd9-11e9-8afa-03411353ed3a.jpg)

**Comment by Su1phur** [comment]
fixed
