### ISSUE TITLE
korean incorporation focus does not work

### ISSUE THREAD

**Issue by watermelon3211** [jespertjee/FR#127]
-->

**Explanation of the issue:**
The focus for 

**Quick questions:**

OS:
HoI4 version: 1.5.4
Führerreich version: 0.2.1
Using Steam? yes 
Were you in multiplayer? no
List other mods used (including FR Music mod): music mod only
Have you changed any files, outside of mods used? no
Checksum (four-letter code at the bottom of your title menu): 2855
[save file.zip](https://github.com/Fuhrerreich/FR/files/2872590/save.file.zip)
[save file.zip](https://github.com/Fuhrerreich/FR/files/2872591/save.file.zip)

Which DLC expansions do you NOT have? i have all

**Steps to reproduce:**

1. play japan

2. chose the focus

**Other info:**
the three options for the focus dont work
in the save file three month have passed sonce the focus 
and event was takem

**Save game:**

[save file.zip](https://github.com/Fuhrerreich/FR/files/2872592/save.file.zip)

**Comment by watermelon3211** [comment]
sorry for the three save files my error

**Comment by Drowse** [comment]
The focus will now give your cores after the national spirit disappears
