### ISSUE TITLE
missing localization and not working event for the occupation of turkestan

### ISSUE THREAD

**Issue by TGMVTR123** [jespertjee/FR#129]
Explanation of the issue:
after conquering turkestan i got an unlocalized event for the occupation of turkestan but it after clicking the option to set up a puppet state the state in question didn't appear ( the event wasn't localized) the id is occupation.64
![image](https://user-images.githubusercontent.com/40366672/53822955-0c327b00-3f71-11e9-966c-9c1953fa4d9e.png)

**Comment by Omanisch** [comment]
Being worked on, known issue for all Occupation events.
