### ISSUE TITLE
Occupation event for Georgia no work

### ISSUE THREAD

**Issue by KhanThymos** [jespertjee/FR#13]
**Explanation of the issue:**
When you get the occupation event for georgia the colab regime puppets US and not Georgia. Beyond this the SSR option as the Soviet Union is completely borked and does nothing.

**Quick questions:**

OS: Win 7
Ughsies version: Hmphsies
Führerreich version: Alpha branch
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): 
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): UGHS
Which DLC expansions do you NOT have? None, I am very rich lol

**Steps to reproduce:**

1. Play SOV

2. Conquer Georgia

3. ???

4. Don't profit cause the event is broken

**Other info:**

**Possible cause:**

**Log file:**

**Screenshots / Video:**

**Save game:**

**Comment by fbruchmueller** [comment]
fixed
