### ISSUE TITLE
Missing Bolivian Revolution news event picture 

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#130]
**Explanation of the issue:**
the world news event I got in early 36 for the Bolivian Revolution has no picture, event id is worldnews. 50  

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/53907517-05c9ff00-4056-11e9-87c8-3d3ee268b8d0.png)

**Comment by Drowse** [comment]
added a photo
