### ISSUE TITLE
USSR broken army path. 

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#132]
**Explanation of the issue:**

tried to test the ussr army path. game kept crushing before I could do anything. 

**Quick questions:**

OS: windows 10
HoI4 version: 1.6
Führerreich version: 0.2 
Using Steam? y
Were you in multiplayer? n 
List other mods used (including FR Music mod): no other mods. 
Have you changed any files, outside of mods used? nope (on debug mode).
Checksum (four-letter code at the bottom of your title menu): 9513
Which DLC expansions do you NOT have? have all. 

**Steps to reproduce:**

1. go the ussr army path, didn't even get to pick any thing.

**Other info:**

had no issues with the game till the crush.  

**Possible cause:**

if I had to guess a broken event, 

**Log file:**

[error.zip](https://github.com/Fuhrerreich/FR/files/2938082/error.zip)

**Save game:**

[SOV_1936_03_01_01 ussr crash .zip](https://github.com/Fuhrerreich/FR/files/2938081/SOV_1936_03_01_01.ussr.crash.zip)

**Comment by fbruchmueller** [comment]
should be fixed
