### ISSUE TITLE
missing localization for japan 

### ISSUE THREAD

**Issue by TGMVTR123** [jespertjee/FR#133]
tag:jap
issue:missing localization
description:the event japan.38 dosent have localization 
![image](https://user-images.githubusercontent.com/40366672/53910424-19746600-4054-11e9-8d84-d3b802bd0898.png)

**Comment by Drowse** [comment]
Added a new description 

"Our attempts to find a peaceful solution to the growing political power of the Japanese Army has failed. When they threatened Japan's democracy we offered them an inch which they saw as an opportunity to take a mile. Slowly but surely Japan's civil government fell to the interests of the military. Under growing internal pressure even the Emperor himself has given into the demands of the military. What ever kind of democracy may have existed in Japan is now just a foot note in history."
