### ISSUE TITLE
Belgium missing minsters and gfx  mess 

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#134]
**Explanation of the issue:**
Playing as Belgium I noticed a lot of mess in the minster area, some are missing and the frames+pp icons don't blend well with the text.  

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/53976688-340c1500-4110-11e9-8a07-a984406af653.png)

![image](https://user-images.githubusercontent.com/48258735/53976758-50a84d00-4110-11e9-83dd-2d14d382f593.png)

![image](https://user-images.githubusercontent.com/48258735/53976840-7d5c6480-4110-11e9-9edc-1d0b3cff02f6.png)

![image](https://user-images.githubusercontent.com/48258735/53976899-99f89c80-4110-11e9-820f-c6ae6f6c5218.png)

**Comment by Drowse** [comment]
seems that mod you're using is making that menu look weird. Looks fine on my end. Fixed the missing portrait though
