### ISSUE TITLE
Missing event localization for Fengtain

### ISSUE THREAD

**Issue by Mattma0514** [jespertjee/FR#135]
**Explanation of the issue:**
Missing localization for event man.1.d of Fengtain Governancy
**Screenshots / Video:**
![fentian localization event 1](https://user-images.githubusercontent.com/48046480/54021729-be657f00-41cb-11e9-8d60-d01ad1e365f8.png)

**Comment by Drowse** [comment]
Copied text from nation description

"With the Anti-Zhili Coaltion being formed in 1924 consisting of the Anhui, Kuomintang, and Fengtian, the war ended disastrously for the Zhili, resulting in a large collapse of the Clique itself. With the Fengtian Clique finally reigning supreme in Beijing, Beiyang had managed to become stable once again with the Zhili remaining a minority in the government. However the relations with the Kuomintang in the south quickly souring, the Northern Expedition against Beiyang began. While the Kuomintang saw initial success, intervention by Shanxi caused their advance to stall, forcing peace between the two biggest governments in China."
