### ISSUE TITLE
CTDs problem

### ISSUE THREAD

**Issue by Mattma0514** [jespertjee/FR#136]
**Explanation of the issue:**
Im playing Fengtian while my game crash on 11th march 1936 unlike the usual 2nd march 1936
**Log file:**
[game.zip](https://github.com/Fuhrerreich/FR/files/2945730/game.zip)
[error.zip](https://github.com/Fuhrerreich/FR/files/2945731/error.zip)
**Save game:**

[autosave.zip](https://github.com/Fuhrerreich/FR/files/2945743/autosave.zip)

**Comment by Omanisch** [comment]
outdated
