### ISSUE TITLE
Production tab stuck

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#139]
**Explanation of the issue:**

the production tab got stuck, the very top item on it gets cut in half, cant see the entire icon/factory count.

(there is no way to scroll up)  

**Quick questions:**

HoI4 version: 1.6
Using Steam? y
Were you in multiplayer? n
List other mods used (including FR Music mod): none 
Have you changed any files, outside of mods used? n 
Checksum (four-letter code at the bottom of your title menu):  9513
Which DLC expansions do you NOT have? I got all of em. 

**Steps to reproduce:**

1. no clue.

**Other info:**

the isusse is present in vanilla hoi4 as well (if any one can label this for me that would be great)

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/54146084-e6591a80-4437-11e9-80ab-6380430739f5.png)

**Comment by KhanThymos** [comment]
Vanilla issue, can't do anything about it sozzle

**Comment by LocalCiggyShop** [comment]
bro what
