### ISSUE TITLE
Occupation event Mongolia

### ISSUE THREAD

**Issue by KhanThymos** [jespertjee/FR#14]
**Explanation of the issue:**
After conquering Germany, I got the occupation event for Mongolia.

**Quick questions:**

OS:
HoI4 version:
Führerreich version:
Using Steam?
Were you in multiplayer?
List other mods used (including FR Music mod):
Have you changed any files, outside of mods used?
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have?

**Steps to reproduce:**

1. Literally no clue

2.

**Other info:**

**Possible cause:**

**Log file:**

**Screenshots / Video:**

**Save game:**

**Comment by Drowse** [comment]
Trigger was pointing to the wrong state 111(Helsinki) NOT 330 (Mongolia's capital)
