### ISSUE TITLE
world news events with no pictures 

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#140]
**Explanation of the issue:**

During my last playthrough I saw a few world news events with no pictures so I put em all together here for you to fix.  (the event id is in the picture) 

**Quick questions:**

Führerreich version: 0.2 
List other mods used (including FR Music mod): none 
Have you changed any files, outside of mods used?no
Checksum (four-letter code at the bottom of your title menu): 9513

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/54146449-ad6d7580-4438-11e9-9287-5ed56bd50dab.png)

![image](https://user-images.githubusercontent.com/48258735/54146492-bc542800-4438-11e9-8e7c-491a010f8a2b.png)

this last one might have already been reported: 
![image](https://user-images.githubusercontent.com/48258735/54146538-d988f680-4438-11e9-95c8-b48ce18c6b3a.png)

**Comment by weis29** [comment]
one more event I forgot: 

![image](https://user-images.githubusercontent.com/48258735/54146702-3ab0ca00-4439-11e9-8814-b52d6f978c1f.png)

**Comment by Drowse** [comment]
added pics for these

![hoi4_17](https://user-images.githubusercontent.com/31998495/63713609-d7530280-c7f4-11e9-8a1a-016961ad676c.png)
