### ISSUE TITLE
BEL, problematic focuses for belgium

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#141]
**Explanation of the issue:**

During my playthrough as Belgium I found 3 focuses with problems in them : 1 had a bad effect (very minor issue) and the other 2 had no effect at all.  

**Other info:**

after doing every focus I looked and saw there was no affect to confirm the issue was real, I was going down the coalition path.  

**Screenshots / Video:**

in this 1st one the effect text isn't 100% just remove the _ no other focus has it. 

![image](https://user-images.githubusercontent.com/48258735/54147137-32a55a00-443a-11e9-94dc-73d569621bdc.png)

the other 2 just have no effect at all: 

![image](https://user-images.githubusercontent.com/48258735/54147213-5ff20800-443a-11e9-8010-cccaaefc47a8.png)

![image](https://user-images.githubusercontent.com/48258735/54147222-641e2580-443a-11e9-9dc1-00cf4222f4db.png)

**Comment by Drowse** [comment]
Added effects for all of these focuses and localized that string
