### ISSUE TITLE
Romania: Missing Country Leader Portrait

### ISSUE THREAD

**Issue by VVA999** [jespertjee/FR#142]
Explanation of the issue:
I was playing as Germany and I noticed that Romania has no portrait for the leader. 
The portrait is the same as when you have an army but no General assigned to it.

OS:
HoI4 version: Ironclad 1.6.1

Führerreich version: 0.2

Using Steam? Yes

List other mods used: The only mod I was using at the time was State Transfer Tool.

Checksum: 9ba0

Screenshot(s):
https://steamuserimages-a.akamaihd.net/ugc/911324212975764826/B252269756E414818655FAD831B2CE760E8422DB/

**Comment by Omanisch** [comment]
outdated
