### ISSUE TITLE
Soviet Union: Typo in the name of the state "Donetsk"

### ISSUE THREAD

**Issue by VVA999** [jespertjee/FR#143]
Explanation of the issue:
There's a typo in the name of the state called "Donetsk". The first letter (D) is not capitalized. 

HoI4 version: 1.6.1
Führerreich version: 0.2
Using Steam? Yes
List other mods used (including FR Music mod): State Transfer Tool
Checksum (four-letter code at the bottom of your title menu):

Screenshot(s):
https://imgur.com/a/yfUd7X4

**Comment by Omanisch** [comment]
Fixed
