### ISSUE TITLE
SOV Kirov decisions show no matter what path

### ISSUE THREAD

**Issue by pokedude750** [jespertjee/FR#144]
**Explanation of the issue:**

**Quick questions:**

OS: Windows 10
HoI4 version: 1.6.2
Führerreich version: 0.2.2
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): Player Led Peace Conferences, Colored Buttons
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): 2609
Which DLC expansions do you NOT have? Have all of them

**Steps to reproduce:**

1. Begin game as the Soviet Union

2. Open decisions menu

**Other info:**

**Possible cause:**

**Log file:**

**Screenshots / Video:**
https://i.imgur.com/5AdgAOy.jpg
**Save game:**

**Comment by fbruchmueller** [comment]
should be fixed
