### ISSUE TITLE
ITA Panfilla Event without owning it. 

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#145]
-->

**Explanation of the issue:**
Playing as Italy I sold the province of Panfilla to turkey to get the buff. however later in my game the went down a path that lets them demand the land from me, so I got an event (as you can see in the pic down the page)  that doesn't make any sense because I don't own the land anymore.  

**Quick questions:**

Have you changed any files, outside of mods used? no 
Checksum (four-letter code at the bottom of your title menu):

**Steps to reproduce:**

1.play as Italy and sell the land to turkey/Greece 

2. have turkey take the route to demand the land from Italy 

**Other info:**

**Possible cause:**

the mod cant tell if I have the land or not and just triggers the event anyways. 

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/48258735/55910836-0a9b4900-5be8-11e9-89c1-b49606ad8073.png)

**Comment by Drowse** [comment]
Checked and pretty sure I removed this event
