### ISSUE TITLE
FENGTIAN lost a event to let JAPAN surrender.

### ISSUE THREAD

**Issue by HarutoLiang** [jespertjee/FR#146]
I was played "ZHILI CLIQUE" and "FENGTIAN GOVERNANCY".
Then I found a question was only ZHILI has a event to let JAPAN surrender but  FENGTIAN has'nt.
The surrender event is in file  "FR_Zhili.txt" named "We've Pushed the Japanese Off the Mainland".

Please add the event for FENGTIAN,too.
It was so sad That anti-JAPAN's war won't be end even though he will join the GERMAN's faction.

OS:
HoI4 version:1.6.2
Führerreich version:Mar.31 version

**Comment by HarutoLiang** [comment]
Hmmmm...
Another question.

The following event "Wu Peifu Demands Our Surrender"say:
every__state{is_core_of = KOR}
will transfer to ZHILI.

But there is no core for KOREA in your map.Cause korea's state will still contorl by JAPAN.
Maybe you should add some core state for KOREA.

**Comment by Drowse** [comment]
The event can now fire for MAN too. Which nation gets it is determined by who is currently at war with Japan AND who has a lower surrender progress. The event also now determines which states to transfer using regions not cores.
