### ISSUE TITLE
GER event with no text 

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#147]
-->

**Explanation of the issue:**

playing as Germany I got this event for something the swiss did: 

event id (as you can see from the pic) is swi.28

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/57450904-706f0500-7268-11e9-9430-92d0546e6bb3.png)

**Comment by weis29** [comment]
another one: 

event id ger 176.d

![image](https://user-images.githubusercontent.com/48258735/57535061-1e9eab80-734a-11e9-8514-5fb27c6f5e0a.png)

**Comment by Omanisch** [comment]
First one fixed, if you would like, put the second one as a different report.
