### ISSUE TITLE
Conquering Germany without using the Algiers Conference causes massive bordergore

### ISSUE THREAD

**Issue by KhanThymos** [jespertjee/FR#15]
**Explanation of the issue:**
I've attached a screenshot to picture what I'm talking about, it's horrible.
![wtf](https://user-images.githubusercontent.com/36137133/50459438-5d1f6500-096b-11e9-82c4-d4226aca4c79.PNG)

**Quick questions:**

OS:
HoI4 version:
Führerreich version:
Using Steam?
Were you in multiplayer?
List other mods used (including FR Music mod):
Have you changed any files, outside of mods used?
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have?

**Steps to reproduce:**

1.

2.

**Other info:**

**Possible cause:**

**Log file:**

**Screenshots / Video:**

**Save game:**

![image](https://user-images.githubusercontent.com/36137133/50459448-66103680-096b-11e9-967c-e209f8c72b07.png)

**Comment by Drowse** [comment]
it's a feature not a bug
