### ISSUE TITLE
White Russia Loc broken

### ISSUE THREAD

**Issue by GDSPathe** [jespertjee/FR#152]
**Explanation of the issue:**
White Russia Loc broken

**Quick questions:**

OS:
HoI4 version: 1.7
Führerreich version: 2.2
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): FR, Lamps Equipment icons 1-3,
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): e995
Which DLC expansions do you NOT have? WTT, MtG

**Steps to reproduce:**

1. Start the game

**Other info:**

The only focus with partially working loc the beginning old guard focus

**Screenshots / Video:**

https://steamcommunity.com/sharedfiles/filedetails/?id=1768519933
https://steamcommunity.com/sharedfiles/filedetails/?id=1768519895
https://steamcommunity.com/sharedfiles/filedetails/?id=1768519841
https://steamcommunity.com/sharedfiles/filedetails/?id=1768519773

**Comment by fbruchmueller** [comment]
fixed
