### ISSUE TITLE
LSMC dosen't work for Argentina, Peru, Belgium, Poland and The Ottomans.

### ISSUE THREAD

**Issue by gamerguest64** [jespertjee/FR#153]
-->

**Explanation of the issue:**
Title

**Quick questions:**

OS:Windows 8.1
HoI4 version:1.7.0
Führerreich version:2.2
Were you in multiplayer?No

**Possible cause:**
I believe something is broken in 2.2 involving LSMC (No news event for it as well)

**Screenshots / Video:**
![hoi4_3](https://user-images.githubusercontent.com/45215875/60760037-27081f80-a037-11e9-9b9b-7a426804ec27.png)
![hoi4_4](https://user-images.githubusercontent.com/45215875/60760025-e3adb100-a036-11e9-927f-001031ebe492.png)
![hoi4_5](https://user-images.githubusercontent.com/45215875/60760028-e7413800-a036-11e9-8031-9d718dab1312.png)
![hoi4_6](https://user-images.githubusercontent.com/45215875/60760029-ea3c2880-a036-11e9-81c7-ed5aafb0186e.png)
![hoi4_7](https://user-images.githubusercontent.com/45215875/60760030-ec9e8280-a036-11e9-85ef-cc46c66a3b02.png)

**Comment by Drowse** [comment]
Fixed the world news event that triggers these. Seems to work fine now
