### ISSUE TITLE
Italy test run bugs and issues

### ISSUE THREAD

**Issue by KhanThymos** [jespertjee/FR#154]
**Explanation of the issue:**
First of all: lots of placeholder icons, this needs to be fixed as having empty bowls represent virtually everything is pretty bad.

2. issue: The event fired by "Mediterranean Light" gets fired for Italy as well, and doesn't seem to do anything.

3. : Alliance with Spanish Popular Front does nothing.

4. : Seek support from Moscow does nothing, or maybe Moscow didn't want to support me, but I have no way of knowing as I didn't get a response event

5. : I can't declare war on Albania after they've refused my annexation demand, because they're still a puppet. I guess it doesn't account for whether you're in a faction either, but I have no way of knowing.

**Quick questions:**

OS: Win 10
HoI4 version: Newest
Führerreich version: France Branch, Newest
Using Steam? yes
Were you in multiplayer? no
List other mods used (including FR Music mod): Player-led and State Transfer
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): 6dc1
Which DLC expansions do you NOT have? Man the Guns

**Steps to reproduce:**

1. Play Italy and choose NatCol path

2. ???

3. Don't profit because Alliance with Popular Front is borked :tfwno:

**Other info:**

**Possible cause:**

**Log file:**
[Logs.zip](https://github.com/Fuhrerreich/FR/files/3382654/Logs.zip)

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/36137133/61062447-8c289000-a3fe-11e9-9900-7ba86c756cd0.png)
![image](https://user-images.githubusercontent.com/36137133/61062464-98145200-a3fe-11e9-85e6-70639af3f88f.png)
![image](https://user-images.githubusercontent.com/36137133/61062484-a2cee700-a3fe-11e9-9251-67882d2836d6.png)

**Save game:**

[ITA_1940_01_21_23.zip](https://github.com/Fuhrerreich/FR/files/3382669/ITA_1940_01_21_23.zip)

**Comment by Drowse** [comment]
90% sure these have been fixed post release
