### ISSUE TITLE
Research Speed - Beijing Government

### ISSUE THREAD

**Issue by emil494** [jespertjee/FR#155]
**Explanation of the issue:**
You accidentally made it so that research speed is reduced instead of increased with Beijing Government's national spirit Illiterate Population.
(It's the same with boats and planes)

![image](https://user-images.githubusercontent.com/14956665/61188986-3fa3b580-a687-11e9-8f82-bccae2876e34.png)

![image](https://user-images.githubusercontent.com/14956665/61188972-11be7100-a687-11e9-9216-030302682849.png)

Thx for the free research though XD

**Comment by KhanThymos** [comment]
Nope, if you research the tanks it'll take ages if you just press research ;)
