### ISSUE TITLE
Focus "An Offer For Deng Xihou" deny event bug

### ISSUE THREAD

**Issue by emil494** [jespertjee/FR#156]
**Explanation of the issue:**
When you do the focus "An Offer For Deng Xihou" as Beijing Government and Sichuan Clique denies you get a war goal on Yunnan Clique, which in my case doesn't exist, instead of getting one on Sichuan Clique.
The event for when they deny also says that you will declare war immediately but you don't
And i don't know if this is a cause of the event but Japan somehow got a war goal on Sichuan Clique.

![image](https://user-images.githubusercontent.com/14956665/61189106-ce650200-a688-11e9-9523-90f427688cbe.png)

**Comment by KhanThymos** [comment]
Fixed, the events in the code were switched.
Thank you for the help!
