### ISSUE TITLE
AutDem Germany name

### ISSUE THREAD

**Issue by rickoscarpablo** [jespertjee/FR#159]
**Explanation of the issue:**
AutDem Germany is led by kaiser Wilhelm III, the party is the monarchist party, the flag is the imperial flag, but it is called a republic

a simple change to German empire is a simple solution (just use the same name as PatAut Germany)

**Steps to reproduce:**

1. as Germany use console command "set_ruling_party Authoritarian_democrat

**Screenshots / Video:**
![FRPRBLM](https://user-images.githubusercontent.com/52924979/61224151-bba10a80-a726-11e9-9a9d-8d072cc12e35.jpg)

**Comment by Omanisch** [comment]
Fixed

**Comment by rickoscarpablo** [comment]
it will be included in the next update?

**Comment by Omanisch** [comment]
Yes.
