### ISSUE TITLE
SWE.106 has no localisation

### ISSUE THREAD

**Issue by KhanThymos** [jespertjee/FR#16]
**Explanation of the issue:**
Same as title

**Quick questions:**

OS:
HoI4 version:
Führerreich version:
Using Steam?
Were you in multiplayer?
List other mods used (including FR Music mod):
Have you changed any files, outside of mods used?
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have?

**Steps to reproduce:**

1.

2.

**Other info:**

**Possible cause:**

**Log file:**

**Screenshots / Video:**

**Save game:**

**Comment by Steffplays123** [comment]
I have added localisation for event SWE.106 and other Swedish events that did not have.
