### ISSUE TITLE
Canada be missing it's ministers and companies.

### ISSUE THREAD

**Issue by ItsRevanAgain** [jespertjee/FR#160]
OS: Windows 7
HoI4 version: 1.7.1
Führerreich version: 0.3
Using Steam? Yes
Were you in multiplayer? Nein
List other mods used (including FR Music mod): Lamps equipment, white map font, smaller outlines, Immersive Music mod allies.
Have you changed any files, outside of mods used? Nein
Checksum (four-letter code at the bottom of your title menu): 
Which DLC expansions do you NOT have?
None

![image](https://user-images.githubusercontent.com/33811430/61297068-59eaaa00-a7d3-11e9-9d1a-4b709dcce466.png)

![image](https://user-images.githubusercontent.com/33811430/61297118-74248800-a7d3-11e9-83a4-2a847c7fabe9.png)

**Comment by Drowse** [comment]
added minister pics and unique companies for Canada
![hoi4_11](https://user-images.githubusercontent.com/31998495/63655114-a90fed00-c738-11e9-9413-c50dbac0b1b7.png)
