### ISSUE TITLE
Scandinavia no flag

### ISSUE THREAD

**Issue by rickoscarpablo** [jespertjee/FR#162]
**Explanation of the issue:**
as Sweden, Scandinavia has no flag

**Steps to reproduce:**

1. command: event sweden.120 option a

**Possible cause:**
no flag in the files

**Comment by Omanisch** [comment]
Can you include a picture please?

**Comment by rickoscarpablo** [comment]
i currently fixed the problem on my own pc with adding a flag from the vanilla game but i'll undo it and send a picture

**Comment by rickoscarpablo** [comment]
![hoi4_2](https://user-images.githubusercontent.com/52924979/62323758-a3641600-b4b0-11e9-80a4-4eebeb794586.png)

**Comment by Drowse** [comment]
added an appropriate flag

![Casdasdaddddpture](https://user-images.githubusercontent.com/31998495/63642104-e27c2600-c66e-11e9-8efe-c6553550f936.PNG)
