### ISSUE TITLE
Russia's Capital Doesn't move

### ISSUE THREAD

**Issue by Angelblue1852** [jespertjee/FR#164]
Explanation of the issue: Russia's Capital doesn't move if they beat the USSR

OS: Windows 10
HoI4 version: 1.7.1
Führerreich version: 0.3.1
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): None
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): 6d5f
Which DLC expansions do you NOT have? None

Steps to reproduce:

1. Play as Russian Republic
2. Fight Against Soviets and Win
3. Capital will stay in Vladivostok

Screenshots / Video:
![IMG_3274](https://user-images.githubusercontent.com/38672184/61557104-5fddc680-aa31-11e9-86ff-472b3e7218f8.jpg)
![IMG_3273](https://user-images.githubusercontent.com/38672184/61557106-5fddc680-aa31-11e9-9486-218418718af0.jpg)

**Comment by Drowse** [comment]
added a hidden event to move the capital to Moscow

`country_event = {
	id = rus.29
	immediate = {log = "[GetDateText]: [Root.GetName]: event rus.29"}

	hidden = yes

	fire_only_once = yes

	trigger = {
		tag = RUS
		RUS = {
			owns_state = 219
		}
	}

	option = {
		RUS = {
			set_capital = 219
		}
	}
}`
