### ISSUE TITLE
Germany gets random events

### ISSUE THREAD

**Issue by Angelblue1852** [jespertjee/FR#167]
Explanation of the issue: Germany keeps get random events at the start of the game.
A: Event about US-Japanese Alliance and War
B: Russia Retakes Homeland from USSR

OS: Windows 10
HoI4 version: 1.7.1
Führerreich version: 0.3.1
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): None
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): 6d5f
Which DLC expansions do you NOT have? None

**Comment by Omanisch** [comment]
Do you have a screenshot?

**Comment by Angelblue1852** [comment]
![20190801002540_1](https://user-images.githubusercontent.com/38672184/62331338-a5ff4500-b489-11e9-97fa-62e2b54fb170.jpg)
![20190801002419_1](https://user-images.githubusercontent.com/38672184/62331339-a5ff4500-b489-11e9-8511-143793421920.jpg)

**Comment by ata-sama** [comment]
Think those are news events. You can disable them at the beginning of your game.

**Comment by Drowse** [comment]
added `is_triggered_only = yes` to these news events
