### ISSUE TITLE
USA Carriers have Japanese ship name options

### ISSUE THREAD

**Issue by Angelblue1852** [jespertjee/FR#168]
Explanation of the issue: The USA somehow gets Japanese names when they are building new carriers.

OS: Windows 10
HoI4 version: 1.7.1
Führerreich version: 0.3.1
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): None
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): 6d5f
Which DLC expansions do you NOT have? None

Screenshots / Video:

![20190801001027_1](https://user-images.githubusercontent.com/38672184/62331368-bca59c00-b489-11e9-846b-783d3946a104.jpg)

**Comment by Drowse** [comment]
History file was pointing to the incorrect ship name categories, Has been fixed

`	create_equipment_variant = {
		name = "Lexington Class"
		type = ship_hull_carrier_conversion_bb
		name_group = USA_CV_HISTORICAL
		parent_version = 0
		modules = {
			fixed_ship_deck_slot_1 = ship_deck_space
			fixed_ship_deck_slot_2 = ship_deck_space
			fixed_ship_anti_air_slot = ship_anti_air_1
			fixed_ship_radar_slot = empty
			fixed_ship_engine_slot = heavy_ship_engine_1
			fixed_ship_secondaries_slot = ship_secondaries_1
			mid_1_custom_slot = ship_deck_space
		}
		obsolete = yes
	}`
