### ISSUE TITLE
German general description localization bug

### ISSUE THREAD

**Issue by White-ses-male** [jespertjee/FR#171]
**Explanation of the issue:**
In every description of a German general where Adam Dressler should be mentioned there reads "[GER.GetLeader]" instead.

**Quick questions:**

Führerreich version: 0.3.1

**Screenshots / Video:**
![hoi4_8](https://user-images.githubusercontent.com/36083604/62640653-bbbdb000-b94a-11e9-9033-03e1a1600207.png)

**Comment by Omanisch** [comment]
Fixed
