### ISSUE TITLE
Fra world event text- too long

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#174]
**Explanation of the issue:**
While playing France you get the option to occupy the canary islands however as you can see the text in the event us too long and too big for the box.

event id worldnews.138
**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/63532287-06c2f000-c513-11e9-9b33-7a042999325d.png)

**Comment by Drowse** [comment]
Rewrote the event 

"As civil war in Spain rages on, a small group of French Marines have occupied the Canary Islands in brief 24 hour operation. The islands are now under French military administration and a naval blockade has been placed around the island by the Marine Nationale. \n\nThe French have stated that the invasion was to ensure the islands were not ravaged by the Spanish civil war, and that the local population had requested foreign protection from Falangist rule. However all sides of the Spanish Civil War have expressed their outrage at a foreign power annexing their territory. \n\nTensions along the Pyrenees have risen sharply, and some believe that further intervention in Spain may soon come."
