### ISSUE TITLE
Ottoman Navy Starting Ships Unarmed (Man the Guns)

### ISSUE THREAD

**Issue by DunkstersMcGee** [jespertjee/FR#175]
**Explanation of the issue:**
Was playing as the Ottomans and noticed that the Ottoman navy uses the default empty ship hull templates (played with Man the Guns enabled), meaning that all of the starting ships are unarmed and unable to actually fight.

![default hulls](https://user-images.githubusercontent.com/42486918/64092386-34c9e080-cd1a-11e9-931e-c0fa910f0e6b.png)

**Comment by DunkstersMcGee** [comment]
Edit: This also happens with the focus to build new cruisers, the two ships are the default empty template, instead of the actual ship class.

**Comment by Drowse** [comment]
TUR naval OOB files now have the appropriate "version_name" parameter for their ships
