### ISSUE TITLE
The last political focus for SocLib France is broken

### ISSUE THREAD

**Issue by White-ses-male** [jespertjee/FR#176]
**Explanation of the issue:**
The last focus in the Social Liberal tree for France requires Social Democrats to be in charge instead.

**Quick questions:**
Führerreich version: 0.3.2

**Screenshots / Video:**
![hoi4_13](https://user-images.githubusercontent.com/36083604/64101897-818fd480-cd77-11e9-8911-3b2768ec4c97.png)

**Comment by darknight1342** [comment]
Fixed
