### ISSUE TITLE
Argentine focus "Ban Collectivism" gives wrong national spirit

### ISSUE THREAD

**Issue by White-ses-male** [jespertjee/FR#178]
**Explanation of the issue:**
"Ban Collectivism" focus for Argentina gives "Censured Reactionaries" national spirit.

**Quick questions:**
Führerreich version: 0.3.2

**Screenshots / Video:**
![hoi4_14](https://user-images.githubusercontent.com/36083604/64438620-19bbef80-d0d1-11e9-8d56-7c5984d4c308.png)

**Comment by Drowse** [comment]
![hoi4_105](https://user-images.githubusercontent.com/31998495/65812984-a82d0980-e183-11e9-8588-9601b680412e.png)
