### ISSUE TITLE
a bizarre issue with poland and french indochina 

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#179]
**Explanation of the issue:**
sooo when right clicking on any country in the game you get to see its minsters in the "details" tab.
 
![image](https://user-images.githubusercontent.com/48258735/64456674-76330500-d0f9-11e9-906d-a9478695cdb4.png)

but for some reason with Poland that spot is empty. 

![image](https://user-images.githubusercontent.com/48258735/64456715-95319700-d0f9-11e9-8d67-6dd925b842d3.png)

is this a thing that's meant to happen? 

idk I might just be crazy here. 

after right clicking on every other country I found out French Indochina has the same issue: 

![image](https://user-images.githubusercontent.com/48258735/64456939-07a27700-d0fa-11e9-9e5f-bd81a3a189f5.png)

looks too random to be intentional.

**Comment by Drowse** [comment]
Countries without ministers won't have that tab when you right click on them. This is functioning as intended.
