### ISSUE TITLE
SOV events lacking description

### ISSUE THREAD

**Issue by Sarah1917** [jespertjee/FR#18]
-->

**Explanation of the issue:** Soviet events lack description, amongs other things the Troika has decided their plan for Soviets rely on mathematics

**Quick questions:**

OS: Windows 7
HoI4 version: 1.5.4
Führerreich version: 0.2 Beta
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): FR Music
Have you changed any files, outside of mods used? Nope
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have? I have all of them

**Steps to reproduce:**

1. Play SOV

2. Enjoy

**Other info:** I totally didn't forget to add pictures

**Possible cause:** Someone didn't write them?

**Log file:**

**Screenshots / Video:**
 http://prntscr.com/m08zho

**Save game:**

**Comment by Sarah1917** [comment]
Soviet.4, Soviet.23, Soviet.9 being the events in question

**Comment by fbruchmueller** [comment]
added loc
