### ISSUE TITLE
World News event with no text. 

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#180]
-->

**Explanation of the issue:**

I am guessing this will get scrapped when the us gets reworked but might be for the best to remove this event till than. 

event id: usanews. 1

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/64458176-4d147380-d0fd-11e9-9298-80ba97252be1.png)

**Comment by Drowse** [comment]
![hoi4_353](https://user-images.githubusercontent.com/31998495/103622699-e9b27580-4eeb-11eb-8b5f-b9e2fdd6d58d.png)
