### ISSUE TITLE
missing leader portrait for an indian country 

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#181]
**Explanation of the issue:**

once India collapses you can see that madras (MDR) is missing a leader pic, the name of the leader is: "Yeswantrao ghorpade"

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/64459345-53581f00-d100-11e9-9e1b-074aa68a98aa.png)

**Comment by Drowse** [comment]
added a portrait
