### ISSUE TITLE
Russia - Request Rifles Doesn't Work

### ISSUE THREAD

**Issue by HerraVofflur** [jespertjee/FR#183]
Explanation of the issue:
As the Russian Republic, the request American rifles decision doesn't fire an event for the US, meaning it doesn't do anything.

Quick questions:
HoI4 version: 1.7.1
Führerreich version: 0.3.2
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): FR, FR Music, Algerian General's Blue Marble
Checksum (four-letter code at the bottom of your title menu):

Steps to reproduce:

1. Go down the Valkist path as Russia

2. Request rifles from America

![20190907151953_1](https://user-images.githubusercontent.com/52018508/64480781-f81b4080-d182-11e9-9b98-eb09f5f0449a.jpg)

**Comment by Drowse** [comment]
Decisions now gives USA event rusinf.16 instead of rusinf.14.
