### ISSUE TITLE
Kingdom of Italy Naval Focuses Broken

### ISSUE THREAD

**Issue by Tphobious** [jespertjee/FR#184]
**Explanation of the issue:**
So currently in the Italian focus tree you have the ability to go down Mare Nostrum and acquire ship research bonuses and decide whether you are going carrier dominate or battleship dominate, problem is that you don't receive any research bonuses cause they still think it's for the old ship models pre MTG.

**Quick questions:**

OS: Windows 10
HoI4 version: 1.7.1
Führerreich version: 0.3.3
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): Many initially, afterwards... none
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): a70a
Which DLC expansions do you NOT have? I have all

**Steps to reproduce:**

1. Start new game playing as Italy

2. (turn on focus.ignoreprereq, nocheck, and autocomplete for faster results) Look at all focuses after Mare Nostrum and you'll notice that they are for the old models of ships and therefore won't apply research bonuses.

**Other info:**
Also some screenshots of what looks to be small typos on two focuses under their effect, figured I add them since you'd be already looking at the focus tree as it is.

**Possible cause:**
Someone forgot to change those xD

**Screenshots / Video:**

![20190914211027_1](https://user-images.githubusercontent.com/55338988/64916625-b3207c80-d735-11e9-949e-897f16c97539.jpg)

![20190914211030_1](https://user-images.githubusercontent.com/55338988/64916628-be73a800-d735-11e9-9eb3-92c9327c20d8.jpg)

![20190914211033_1](https://user-images.githubusercontent.com/55338988/64916629-c3d0f280-d735-11e9-8ff3-9dd328d158f9.jpg)

![20190914211109_1](https://user-images.githubusercontent.com/55338988/64916641-f7138180-d735-11e9-834b-90737c7f9046.jpg)

![20190914211707_1](https://user-images.githubusercontent.com/55338988/64916645-0266ad00-d736-11e9-8c22-9432c534ec24.jpg)

**Comment by Drowse** [comment]
Bonuses now apply to the correct category.
