### ISSUE TITLE
Germany does not get it's proper cores on 0.3.3 Latim Sisters

### ISSUE THREAD

**Issue by Gukpard** [jespertjee/FR#186]
On the current version Germany does not get cores on Alsace Lorraine, Saarbrucken, Holstein, Luxembourg, Trentino and Elpen Malmedy.

This can be fixed by adding these cores on the "Claims in the west focus" and "demand sudtyrol", as the regions above were part of Germany or austria before WWI and could be cored.

OS: Windows 10
HoI4 version: Hydra v1.7.1. (87c8)
Führerreich version: 0.3.3.
Using Steam? Yes.
Were you in multiplayer? No.
List other mods used (including FR Music mod): None.
Have you changed any files, outside of mods used? No.
Checksum (four-letter code at the bottom of your title menu): Hydra v1.7.1. (87c8)
Which DLC expansions do you NOT have? I have all.

Other info: France capitulated so quick that they didn't fled to Algiers, I simple annexed them. However on another gameplays were they fled and I invaded Algeria the same non core error happened.

**Comment by Drowse** [comment]
all states should be added now
