### ISSUE TITLE
Disappearing companies

### ISSUE THREAD

**Issue by Sarah1917** [jespertjee/FR#19]
-->

**Explanation of the issue:** While playing the Soviets I put some arms companies to cut my production costs and they disappeared off the screen

**Quick questions:**

OS: Windows 7
HoI4 version: 1.5.4
Führerreich version: 0.2 Beta
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): FR Music
Have you changed any files, outside of mods used? Nope
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have? I have all of them

**Steps to reproduce:**

1. Play SOV

2. Choose companies

**Other info:**

**Possible cause:** I'm not sure but I've seen this bug in Argentina in KR too

**Log file:**

**Screenshots / Video:**
http://prntscr.com/m0bbro

**Save game:**

**Comment by Drowse** [comment]
Seems to work fine for me
