### ISSUE TITLE
Poland - Lithuanian unrest idea after giving Lithuania to Germany

### ISSUE THREAD

**Issue by Baeldaeg** [jespertjee/FR#224]
**Explanation of the issue:**
Playing as Poland, after Germany demands Lithuania, and you let them have it, you still have the Lithuanian unrest idea.

**Steps to reproduce:**

1. As Poland run event ger.133

2. Choose option one

**Other info:**

Adding `remove_ideas = POL_lithuanian_unrest` to ger.133.a would fix it I think. 
Possibly add `remove_ideas = POL_lithuanian_unrest_stagnant`
and `remove_ideas = POL_lithuanian_unrest_less_bad` too.

**Possible cause:**
No code to remove the idea.

**Comment by Drowse** [comment]
added a cancel trigger for these ideas
