### ISSUE TITLE
"invalid ideaInvalid Idea modest legislative support removed" keeps showing up

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#229]
**Explanation of the issue:**
during a germany game, the massege about "Invalid Idea modest legislative support removed" keeps showing up, its really annoying and hurts the flow of the game. 

![image](https://user-images.githubusercontent.com/48258735/71252337-60a2bd80-232d-11ea-947d-b83ebd4d1836.png)

**Comment by Drowse** [comment]
It's been removed
