### ISSUE TITLE
SAF paul Bptha is pm instead of D.F Malan  

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#232]
**Explanation of the issue:**
As you can see from the Picture D.F Malan is meant to lead SAF when this event triggers but that is not the case. 

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/72756735-d45b1300-3bd6-11ea-8182-9ffa66ff4693.png)

**Comment by jespertjee** [comment]
Gonna presume this was fixed
