### ISSUE TITLE
SAF loc issue. 

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#233]
**Explanation of the issue:**
a minor bug with event "worldnews.142", as you can see from the pic the line goes behind the text making it a bit hard to read. not something big but should be fixed before the update. 

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/72756922-58ad9600-3bd7-11ea-94da-789c10c7109d.png)

**Comment by jespertjee** [comment]
Fixed
