### ISSUE TITLE
Outdated Game and Missing Text.

### ISSUE THREAD

**Issue by ImperialBrit** [jespertjee/FR#234]
**Explanation of the issue:**
The game seems outdated with missing text and missing music and it seems to be using an old mod.
![Issue](https://user-images.githubusercontent.com/59508506/75484366-93f27000-59a0-11ea-9fb8-22aaab5444c0.PNG)
OS: Windows 10
HoI4 version:1.9.0
Führerreich version: It says its 0.3.3
Using Steam?: yes
Were you in multiplayer? no
List other mods used (including FR Music mod): FR Music, State Transfer Tool. And some other cheat mods such as easybuff and player led confrences.
Have you changed any files, outside of mods used?: No
Checksum (four-letter code at the bottom of your title menu):5122
Which DLC expansions do you NOT have?: The new one la resistance.

**Comment by Arslet** [comment]
Some of those issues will be fixed in 1.9.1, the rest we will fix for 0.4.

**Comment by jespertjee** [comment]
Localization seems fine in 0.4 on 1.9.1, I'm going to declare this one fixed
