### ISSUE TITLE
British focus tree can't bypass "Removing the Final Roadblock" if you already vassalize Siam

### ISSUE THREAD

**Issue by Fuyukiri** [jespertjee/FR#236]
HoI4 version: 1.9.1
Führerreich version: latest
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): No
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT **have?**

**Steps to reproduce:**

1. French republic declared  war on Siam then occupied it. After that declared war on British empire (player).

2. After defeated France, I automatically got All of Siam. Then the focus tree can't bypass "Removing the Final Roadblock".

**Comment by jespertjee** [comment]
fixed
