### ISSUE TITLE
Estonia has cores on Latvia.

### ISSUE THREAD

**Issue by Olmek987** [jespertjee/FR#239]
HoI4 version - 1.9.1
Führerreich version - Latest
Using Steam? - Yes
Were you in multiplayer? - Nope
List other mods used - Toolpack 1.9
Have you changed any files, outside of mods used? - No
Checksum - 811c
Which DLC expansions do you NOT have?

Screenshots / Video:
![image](https://user-images.githubusercontent.com/42069250/78991154-8e0fb300-7b38-11ea-9ebb-14a379c6ec24.png)

**Comment by jespertjee** [comment]
Fixed
