### ISSUE TITLE
The future of industry focus for MAN missing shine

### ISSUE THREAD

**Issue by karrot1** [jespertjee/FR#24]
**Explanation of the issue:**
It's... it's missing its shine. That's all there is to it

**Steps to reproduce:**

1. Take the focus

2. Look at it

**Possible cause:**
Someone forgot to add a shiny version

**Screenshots / Video:**
![image](https://user-images.githubusercontent.com/6722625/50564264-a10ac500-0cf1-11e9-91e7-3b7ca4d3dc69.png)

**Comment by Drowse** [comment]
works fine for me
