### ISSUE TITLE
Simferopol city is in the wrong place

### ISSUE THREAD

**Issue by N3xtery** [jespertjee/FR#242]
**Explanation of the issue:** On the map Simferopol is on the coast, but in reality it's not and it should be in the centre of Crimea

HoI4 version: 1.9.1
Führerreich version: 0.4.1
Using Steam? Yes
List other mods used (including FR Music mod): FR Music mod and that's it
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): 5571

**Screenshots / Video:**
![20200412123355_1](https://user-images.githubusercontent.com/38759491/79069380-622a3400-7cd6-11ea-8973-9ecd34e29c75.jpg)

**Comment by Drowse** [comment]
VPs just place themselves in the center of a province so I don't think this is much of an issue
