### ISSUE TITLE
Wrong Text For The Event

### ISSUE THREAD

**Issue by gamerguest64** [jespertjee/FR#248]
**Explanation of the issue:**
As the UK I demanded for Nepal and Bhutan to be integrated into British Raj, Nepal accepted, Bhutan did not. This is the event I got about Bhutan rejecting my demand.

**Quick questions:**

OS:Windows 8.1
HoI4 version:1.9.1
Führerreich version:0.4.1
Using Steam?Yes
Were you in multiplayer?No
List other mods used (including FR Music mod):No
Have you changed any files, outside of mods used?No
Checksum (four-letter code at the bottom of your title menu):5771
Which DLC expansions do you NOT have?I have them all

**Screenshots / Video:**
![hoi4_43](https://user-images.githubusercontent.com/45215875/79669341-8c429100-81c3-11ea-9c38-1e42841c7aa2.png)

**Comment by Drowse** [comment]
Assigned the correct description to this event
