### ISSUE TITLE
missing german minsters 

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#249]
**Explanation of the issue:**

the following German minsters are missing a pic: 

lugo Brentano 
walther steffens 
and gotthard heinrici 
 
**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/79672135-0d0b8800-81d8-11ea-8d3d-54b42dd523bc.png)

![image](https://user-images.githubusercontent.com/48258735/79672152-244a7580-81d8-11ea-80cf-7161f20bb65c.png)

![image](https://user-images.githubusercontent.com/48258735/79672160-35938200-81d8-11ea-9989-5c4cb6075985.png)

**Comment by Drowse** [comment]
Removed ministers cause I'm too lazy for a real fix
