### ISSUE TITLE
CZE event needs fix 

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#250]
-->

**Explanation of the issue:**

as Germany when you get hold of the Sudetenland the event is fine but as you can see from the pic at the bottom it says "cze.6.a, should be an easy fix. 

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/79672211-a0dd5400-81d8-11ea-996c-528e95aaa4c5.png)

**Comment by Drowse** [comment]
Fixed the code typo causing this
