### ISSUE TITLE
German focus not needed anymore

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#251]
-->

**Explanation of the issue:**

with the removal of Belarus from the game I think the focus "mission to minsk" should be removed as well no way to use it.

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/79672268-0df0e980-81d9-11ea-8675-f90e22d7356a.png)

**Comment by Drowse** [comment]
Going to consider this closed since bypass trigger is working fine for this scenario
