### ISSUE TITLE
Führerreich Dosent Work Correctlly.

### ISSUE THREAD

**Issue by abdelkrim115** [jespertjee/FR#255]
**Explanation of the issue:**
When A Start The Mod To Chose Country To Play With I see To Much Nations Dosent Have Names
And See a Weird Names Like RULE_GROUP_RANDOMIZER And RE_NEW_GAME. And To Much Bugs
Letting The Mod Unplayable.

OS: Windows 10
HoI4 version: 1.9
Führerreich version: 0.4
Using Steam? - No
Were you in multiplayer? - No
List other mods used (including FR Music mod): Player led Peace Conferences
Have you changed any files, outside of mods used? - No
Checksum (four-letter code at the bottom of your title menu): 1bd4
Which DLC expansions do you NOT have? I have all the dlc

**Steps to reproduce:**

Start New Game

Select Country

Click Other Countries

**Other info:**
I Have A Cracked Game Not The Original. And I Install The Mod From Skymods.

Screenshots / Video:
![hoi4_31](https://user-images.githubusercontent.com/54541274/80395107-aa3a8080-88aa-11ea-9593-97ce1d5dacbf.png)

![hoi4_32](https://user-images.githubusercontent.com/54541274/80395295-e4a41d80-88aa-11ea-9326-28d9c3fed906.png)

![hoi4_33](https://user-images.githubusercontent.com/54541274/80395400-09989080-88ab-11ea-9b31-aaf40a569556.png)

![hoi4_34](https://user-images.githubusercontent.com/54541274/80395539-42d10080-88ab-11ea-802e-9e5cd8bdce7f.png)

![hoi4_35](https://user-images.githubusercontent.com/54541274/80395645-6bf19100-88ab-11ea-86ef-097cf9446e1e.png)

![hoi4_37](https://user-images.githubusercontent.com/54541274/80395729-8d527d00-88ab-11ea-819a-fa7321468fa6.png)

![hoi4_38](https://user-images.githubusercontent.com/54541274/80395929-cee32800-88ab-11ea-9e60-50720b97432f.png)

![hoi4_39](https://user-images.githubusercontent.com/54541274/80396020-efab7d80-88ab-11ea-86b3-4f5284b91969.png)

![hoi4_40](https://user-images.githubusercontent.com/54541274/80396108-136ec380-88ac-11ea-9366-97f36fcf0e7c.png)

**Comment by Arslet** [comment]
Please update to 1.9.1, the mod is not compatible with 1.9. This will fix the issue.

**Comment by darknight1342** [comment]
Not only that, you're downloading the mod from an unofficial source as well as the mods, not to mention you're running unofficial submods with FR. We aren't liable to help you for those reasons because there is nothing we can do
