### ISSUE TITLE
After I made the USA my dominion and I finished the Imperial Fed path for sm reason the US annexed Seine Inferieure 

### ISSUE THREAD

**Issue by kaiserwilllie** [jespertjee/FR#256]
The title explains everything
![Screenshot (629)](https://user-images.githubusercontent.com/63571915/81646078-7d748600-93df-11ea-83c6-c5eeadc4207c.png)
Note I annexed the US after they annexed that part of France

**Comment by Drowse** [comment]
It seems that 743 was a state in Mexico and when the ID 743 got reused in France no one updated the old code until now
