### ISSUE TITLE
France has requested return of their territory while at war with me.

### ISSUE THREAD

**Issue by RandomGuy45678** [jespertjee/FR#258]
**Explanation of the issue:**
Self-explanatory from the title. While at war with the Entente, I have received an event "French Republic requests the return of their core territory". The country I'm playing is socialist Spain in the Internationale.

**Quick questions:**

OS: Windows
HoI4 version: 1.9.2
Führerreich version: 0.4.2
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): None
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): 
Which DLC expansions do you NOT have? La Resistance

**Steps to reproduce:**

1.

2.

**Other info:**

**Possible cause:**
The mod doesn't actually check that the country that gets the event to request cores, gencores.1, is at peace with the country that sends it

**Log file:**

**Screenshots / Video:**

**Save game:**

**Comment by Drowse** [comment]
Added a check to see if the country is at war before that event fires now
