### ISSUE TITLE
RUS- world news event missing a pic and has the headline inside the main text

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#266]
**Explanation of the issue:**

this news event has a missing picture and its headline is really distracting: You are unable to read the event 

event id: worldnews.113

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/85210157-4e3e2680-b346-11ea-9799-018798fd85d0.png)

**Comment by Drowse** [comment]
Shortened the title to fit and reimplemented the missing news event image
