### ISSUE TITLE
RUS- the focus "A modern engine of war" has a missing effect

### ISSUE THREAD

**Issue by weis29** [jespertjee/FR#267]
**Explanation of the issue:**

As you can see from the picture the effect for the focus "A modern engine of war" it's not implemented correctly it has no effect on Infantry equipment end towed artillery

**Screenshots / Video:**

![image](https://user-images.githubusercontent.com/48258735/85210220-b3921780-b346-11ea-83c8-c6336cea55f9.png)

**Comment by Angelblue1852** [comment]
I just took a look at this issue myself. It looks like it works, maybe they just had to do that like it is to keep it working properly. Cause from what I've seen, if they took out those lines to fix it, you'd lose the infantry and artillery bonuses.

**Comment by Drowse** [comment]
Yeah it does work. The issue seems to be that the "Modify idea by..." tool tip doesn't like it when the two events you're trying to swap have the same modifier values.
