### ISSUE TITLE
USA- No Naval Bomber Pictures

### ISSUE THREAD

**Issue by Angelblue1852** [jespertjee/FR#269]
Explanation of the issue: USA has no naval bomber pictures.

OS: Windows 10
HoI4 version: 1.9.3
Führerreich version: 0.4.2
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): None
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu): 8580
Which DLC expansions do you NOT have? None

Possible cause: The Interface file seems to have the wrong names for the pictures of naval bombers in the interface folders.

Screenshots / Video:

![Error2](https://user-images.githubusercontent.com/38672184/86416196-5035ad00-bc97-11ea-8da5-414cf4a9b0a0.PNG)
![Error1](https://user-images.githubusercontent.com/38672184/86416200-50ce4380-bc97-11ea-969a-3b653ec1f0a7.PNG)

**Comment by Drowse** [comment]
Yeah I fixed the typo
