### ISSUE TITLE
Ottoman puppeted PatAut Italy has Afghanistani flag

### ISSUE THREAD

**Issue by White-ses-male** [jespertjee/FR#270]
**Explanation of the issue:**
Ottoman Empire got most of Italy and made them a puppet and they seem to have Afghanistani flag, not sure if this applies to other possible PatAut nations than Ottomans.

**Steps to reproduce:**

1. Puppet Italy as PatAut Ottomans

**Screenshots / Video:**
![hoi4_162](https://user-images.githubusercontent.com/36083604/89993409-57d17400-dc8f-11ea-9c34-0a12322e73a3.png)

**Comment by Drowse** [comment]
I looked at the files and couldn't see any thing that would cause this and I've never seen the issue myself. I'm going to close the issue for now but if anyone sees it again feel free to submit another issue
