### ISSUE TITLE
Soviet army is duplicated after completing the "Nation is reunited" focus

### ISSUE THREAD

**Issue by heck-fraud** [jespertjee/FR#271]
-->

**Explanation of the issue:**
After completing the focus "Nation is Reunited" after Tukhachevsky's coup the soviet army duplicates.

**Quick questions:**

OS: Microsoft 10
HoI4 version: 1.9.3
Führerreich version: 0.4.2
Using Steam? yes
Were you in multiplayer? no
List other mods used (including FR Music mod): FR Music mod
Have you changed any files, outside of mods used? no
Checksum (four-letter code at the bottom of your title menu): a7a4
Which DLC expansions do you NOT have? all except Poland: united and ready, Historical German Portraits, Rocket Artillery Unit Pack, and the Anniversary DLC

**Steps to reproduce:**

1. Resolve the power struggle in the Soviet union with Tukhachevsky's coup

2. Work your way down the military coup foci and complete the "Nation is Reunited" focus

3. By the power of socialism the Red Army is duplicated

**Other info:**
Seems to happen to because the focus spawns divisions, and the soviet union doesn't lose any divisions in the process of the coup.

**Possible cause:**
Poor implementation of code. The problem seems to be that completing the focus spawns divisions. The fix should be pretty easy: either get rid of the unit spawn or make the event "Divisions are deserting!" that happens after Frunze dies make you lose divisions. 

**Screenshots / Video:**

(First three are from a game with graphical mods in which i noticed the problem, last two are only with the FR Music mod. I included the first two to make it clear that the problem arises after the focus is completed, and the third one to show that the unit spawn is the same. The problem is somewhere in FR's code, probably with the code associated with the focus "nation is Reunited" in the military coup focus chain)

![20200813204020_1](https://user-images.githubusercontent.com/69657193/90211302-4dfa5e80-ddbe-11ea-9108-af482b029325.jpg)
![20200813204050_1](https://user-images.githubusercontent.com/69657193/90211328-5f436b00-ddbe-11ea-8da8-f0e7375aeb66.jpg)
![20200813204303_1](https://user-images.githubusercontent.com/69657193/90211537-fc060880-ddbe-11ea-9acc-02838a642b85.jpg)
![20200813233144_1](https://user-images.githubusercontent.com/69657193/90211665-5c954580-ddbf-11ea-9ca3-e07fc8d590c4.jpg)
![20200813233532_1](https://user-images.githubusercontent.com/69657193/90211688-6fa81580-ddbf-11ea-9039-ae6b41b44ea5.jpg)

**Comment by Angelblue1852** [comment]
Yep. The focus loads a new order of battle for an unknown reason. Removing it should fix the problem.

**Comment by Drowse** [comment]
Yes. I had removed the delete template commands earlier in USSR's event tree because they were causing weird crashes but it seems I missed the load OOB command from later on.
