### ISSUE TITLE
British Raj Divided to the Swiss and British

### ISSUE THREAD

**Issue by DerpStar64** [jespertjee/FR#272]
OS: Windows
HOI4 Version: Husky v1.9.3 (a7a4)
Führerreich version: 
Using Steam: Yes
Multiplayer: No
Other mods used: Player-Lead Peace Conferences, State Transfer Tool, Colored Puppets & Country Specific Names, and No Puppet Divisions.
Files Changed: None
Checksum: a7a4
DLC not owned: La Resistance

Steps to Reproduce:
1. Afghanistan goes to war with the British during Indian Revolt.
2. Afghanistan takes both Peshawar and Quetta
3. Indian Revolt annexed by the British Empire, not back into the Raj
4. Wait until Switzerland gets the province of Punjab (no clue when it happens)

Other Info:
I gave the provinces of Savoy and Aosta Valley to Switzerland and returned them to France and Italy all while paused.
Possible Cause: State Transfer Tool
Screenshot
![20200829174738_1](https://user-images.githubusercontent.com/50438430/91642003-c8161e80-ea1f-11ea-8ae7-f73c12a75863.jpg)

**Comment by DerpStar64** [comment]
Once I reloaded my game the British Indian territories were returned to the Raj, Punjab stayed Swiss.

**Comment by Drowse** [comment]
India has been reworked. This should no longer be an issue
