### ISSUE TITLE
The 1936 elections for Norway won't bypass if you elect the moderate AP.

### ISSUE THREAD

**Issue by gamerguest64** [jespertjee/FR#277]
Führerreich version: 0.5

**Steps to reproduce:**

1.Elect the moderate AP for Norway.

![hoi4_619](https://user-images.githubusercontent.com/45215875/112036930-dc4f7380-8b49-11eb-9a95-d3fd43bd7ded.png)
:**

**Comment by darknight1342** [comment]
Fixed internally, will be in 0.5.1
