### ISSUE TITLE
The Naval Summit Event is over in less than a day JAP

### ISSUE THREAD

**Issue by KhanThymos** [jespertjee/FR#33]
**Explanation of the issue:**
The events in the American Naval Summit trigger each other instantly after the other, despite saying for example "we'll discuss this tomorrow". Quick sleep you had there chief

**Quick questions:**

OS:
HoI4 version:
Führerreich version:
Using Steam?
Were you in multiplayer?
List other mods used (including FR Music mod):
Have you changed any files, outside of mods used?
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have?

**Steps to reproduce:**

1. Play Japan lol

2.

**Other info:**

**Possible cause:**

**Log file:**

**Screenshots / Video:**

**Save game:**

**Comment by Su1phur** [comment]
Fixed by adding days
