### ISSUE TITLE
JAP can force USA in to a faction

### ISSUE THREAD

**Issue by KhanThymos** [jespertjee/FR#34]
**Explanation of the issue:**
As pictured in the image I've attached, the Naval Summit simply allows Japan to force the US into a faction without consent from them.

**Quick questions:**

OS:
HoI4 version:
Führerreich version:
Using Steam?
Were you in multiplayer?
List other mods used (including FR Music mod):
Have you changed any files, outside of mods used?
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have?

**Steps to reproduce:**

1.

2.

**Other info:**

**Possible cause:**

**Log file:**

**Screenshots / Video:**
![jap test](https://user-images.githubusercontent.com/36137133/50575228-98ea7c80-0dfa-11e9-82d5-376ad885e073.png)

**Save game:**

**Comment by fbruchmueller** [comment]
Also please adopt it as 0.2 will release without the USA rework, so no Mexico joining

**Comment by Su1phur** [comment]
USA will be the faction leader now
