### ISSUE TITLE
Japan denied my request for aid militarily and economically

### ISSUE THREAD

**Issue by fbruchmueller** [jespertjee/FR#36]
**Explanation of the issue:**
I used both foci that asks Japan to help me, one military and the other economically. Both of them were denied which is really weird as Japan should accept it most or all the time imo.

OS:
HoI4 version: 1.5.4
Führerreich version: indev
Have you changed any files, outside of mods used? just soviet related ones
Which DLC expansions do you NOT have? none

**Steps to reproduce:**

1.Play Manchuria

2.Go for the path that unlocks the focus "Awaken Pan-Asianism"

3. Choose both foci that asks Japan for help and get denied maybe.

**Comment by Drowse** [comment]
seems like he scrapped it. dead issue
