### ISSUE TITLE
Crash as SOV

### ISSUE THREAD

**Issue by charlesthe50th** [jespertjee/FR#39]
**Explanation of the issue:**
While playing as SOV and going to war with Poland, I saved my game and quit. After opening the game and loading the save, my game crashed while loading.

**Quick questions:**

OS: Windows
HoI4 version: 1.5.4
Führerreich version: Dev
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): FR music mod
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have? Death/Dishonor

**Steps to reproduce:**

1. Load the save I give.

**Log file:**

[error.zip](https://github.com/Fuhrerreich/FR/files/2736932/error.zip)

**Screenshots / Video:**

**Save game:**

[SOV_1938_12_21_16.zip](https://github.com/Fuhrerreich/FR/files/2736935/SOV_1938_12_21_16.zip)

**Comment by Drowse** [comment]
ehh probably a one time thing. Saving and reloading can cause stability issues
