### ISSUE TITLE
Phoenician focus tree ain't working

### ISSUE THREAD

**Issue by Sarah1917** [jespertjee/FR#42]
Explanation of the issue: Despite the fact Phoenicia went with the workers' uprising nothing has changed

**Quick questions:**

OS: Windows 7
HoI4 version: 1.5.4 
Führerreich version: 0.2 beta
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): FR Music mod
Have you changed any files, outside of mods used? No
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have?

**Steps to reproduce:**

1. Take a peek or play as Phoenicia

2. Have the focus tree do nothing

Other info: The tree be hella broken 

Possible cause: Improper coding or lack of it?

**Log file:**

**Screenshots / Video:**
 http://prntscr.com/m6jdtz , http://prntscr.com/m6je3r

**Save game:**

**Comment by KhanThymos** [comment]
Phoenicia is not ready for testing lol
