### ISSUE TITLE
When Romania releases Hungary as a puppet, Hungary gets its land back

### ISSUE THREAD

**Issue by karrot1** [jespertjee/FR#43]
**Explanation of the issue:**
I mean, that's it

**Steps to reproduce:**

1. As Romania, annex Hungary

2. Release Hungary as a puppet

3. Be upset when they get their land back

**Possible cause:**
The event releases all of Hungary's claimed land, instead of just the land they had before the war

**Screenshots / Video:**
![20190109143124_1](https://user-images.githubusercontent.com/6722625/51127586-cf10fe80-17f3-11e9-9aae-3135ea82f023.jpg)

**Comment by Drowse** [comment]
added a check to the bottom of that event

`		if = {
			limit = {
				tag = ROM
				HUN = {
					is_puppet_of = ROM
				}
			}
			if = {
				limit = {
					HUN = {
						owns_state = 154
					}
				}
				ROM = {
					transfer_state = 154
				}
			}
			if = {
				limit = {
					HUN = {
						owns_state = 83
					}
				}
				ROM = {
					transfer_state = 83
				}
			}	
			if = {
				limit = {
					HUN = {
						owns_state = 762
					}
				}
				ROM = {
					transfer_state = 762
				}
			}
		}`
