### ISSUE TITLE
When Tukhachevsky is overthrown, SOV's party popularity goes down to 15% 

### ISSUE THREAD

**Issue by karrot1** [jespertjee/FR#44]
**Explanation of the issue:**
When Tukhachevsky is overthrown, the guy who replaces him has no party poularity

**Steps to reproduce:**

1. Get Tukachevsky overthrown

2. Press F for your party poularity

**Possible cause:**
No events to raise your party popularity after the party change

**Screenshots / Video:**
![20190107204457_1](https://user-images.githubusercontent.com/6722625/51127780-5d858000-17f4-11e9-8a9a-ea09edd4805e.jpg)

**Comment by fbruchmueller** [comment]
fixed
