### ISSUE TITLE
Japan - Localisation Issues

### ISSUE THREAD

**Issue by SuperMarks** [jespertjee/FR#55]
-Many Companies remain unlocalised.
-Japan does not have standardised names for new fleets that are created, resulting in any new fleet being called "FLEET_NAME"
-jap_break_wnt_in_secret has no loc
-jap_call_the_san_fran_summit has no loc
-Many national foci have no description loc
-Many event remains unlocalised, including but not limited to: japflav.1, japflav.2, japflav.3, japflav.4 and jappol.1
-jap_national_industry_interference_act has no loc
-Hirota-Eden Pact focus name should be changed, as Eden is only a backbencher for the Conservative Party(UK) in most games and has little influence on Government policy.
-Specialised Bomber Pilots National Spirit has incorrect localisation
-Long Lance Torpedoes National Spirit has incorrect localisation

**Comment by Drowse** [comment]
fixed missing loc
