### ISSUE TITLE
Missing loc

### ISSUE THREAD

**Issue by TNTDragon11** [jespertjee/FR#6]
**Explanation of the issue:**
Event Soviet History is missing localization. Event Description is soviet.1.d
Death of Lenin is missing description
Emergency Meeting of the Congress of Soviet- Kirovs choice description says "thatr reveals"
Kollontai removed from podium- Says "of" instead of "off" in the description
Shliapnikov makes a speech before delegates-"but if don't do" "loose" instead of "lose"
Kirov becomes Premier- "Kirov has go"
Industrial Party Trial-We trialing

**Quick questions:**

Führerreich version: Test Build, Soviet branch
Using Steam? Yes
Were you in multiplayer? No
List other mods used (including FR Music mod): None
Have you changed any files, outside of mods used? Nope
Which DLC expansions do you NOT have? None

**Steps to reproduce:**

1. Start the Game as Soviets

2. Wait I guess?

**Other info:**

**Possible cause:**

**Log file:**

**Screenshots / Video:**

**Save game:**

**Comment by fbruchmueller** [comment]
fixed
