### ISSUE TITLE
Japan Suggestions - Increase Starting IC

### ISSUE THREAD

**Issue by SuperMarks** [jespertjee/FR#64]
Due to Japan starting with such low IC, and suffering the same affliction as the UK (in that they cannot build factories (when the LSMC stuff functions correctly) for a while), they fall behind other powers significantly. Their low starting IC compounds this issue further.

**Comment by Drowse** [comment]
Japan starts with 81 factories, placing them as the worlds 4th largest economy right above Italy(77 Factories)
