### ISSUE TITLE
Japan- Washington Naval Treaty Weird Thing

### ISSUE THREAD

**Issue by donbg** [jespertjee/FR#65]
You get an event in like early January asking if you'd like to renew an alliance with Britain. If you choose to join Britain's faction, you lose the national spirit "Washington Naval Treaty". Yet, for some reason, you still get the decision to Break the Washington Naval Treaty despite not having that national spirit. 
![image](https://user-images.githubusercontent.com/40672374/51280999-10aece80-19d9-11e9-8fd9-eb811232b91d.png)

**Comment by donbg** [comment]
Actually, in regards to that, this alliance with Britain thing is very strange. I got an event in the beginning of the game called the "Hirota-Eden Pact" with very vague description about Britain wanting to rejoin an alliance. I did not have any events before that except the intro event. I clicked that I wanted to join their alliance. A week later I get this event: 
![image](https://user-images.githubusercontent.com/40672374/51281162-887cf900-19d9-11e9-9dcd-ed133c95e011.png)

This event concerns some summit or something like that but I had no idea that there was even a summit going on.

**Comment by donbg** [comment]
This is in January 8th btw. I got the "Hirota-Eden" event in like the 3rd of January and it didn't have any context and just popped up.

**Comment by donbg** [comment]
Also I can do the San Francisco Summit without having the "Washington Naval Treaty" national spirit and while being in an alliance with Britain.

**Comment by donbg** [comment]
![image](https://user-images.githubusercontent.com/40672374/51281965-d135b180-19db-11e9-9db7-e84cf5b94f04.png)
Alright I haven't done any of these focuses but managed to ally Britain (and supposedly end this "Kyoto Summit" or whatever its name is) and then switch sides and ally the USA in the Pacific Coalition

**Comment by Drowse** [comment]
Reworked these events to function better. both paths are now functional
