### ISSUE TITLE
Austria gets annexed by Germany even if Austria is currently in a war

### ISSUE THREAD

**Issue by KhanThymos** [jespertjee/FR#66]
**Explanation of the issue:**
I was playing as Hungary and declared war on Valkist Austria for Burgenland, Austria then got annexed by Germany about 1 or 2 days into the war.

**Quick questions:**

OS:
HoI4 version:
Führerreich version:
Using Steam?
Were you in multiplayer?
List other mods used (including FR Music mod):
Have you changed any files, outside of mods used?
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have?

**Steps to reproduce:**

1.

2.

**Other info:**

**Possible cause:**

**Log file:**

**Screenshots / Video:**

**Save game:**

**Comment by Drowse** [comment]
Working as intended I believe
