### ISSUE TITLE
Japan has been stuck on "Constitutional Crisis" the entire game

### ISSUE THREAD

**Issue by KhanThymos** [jespertjee/FR#73]
**Explanation of the issue:**
Same as title. It's 1941

**Quick questions:**

OS:
HoI4 version:
Führerreich version:
Using Steam?
Were you in multiplayer?
List other mods used (including FR Music mod):
Have you changed any files, outside of mods used?
Checksum (four-letter code at the bottom of your title menu):
Which DLC expansions do you NOT have?

**Steps to reproduce:**

1.

2.

**Other info:**

**Possible cause:**

**Log file:**

**Screenshots / Video:**

**Save game:**

![image](https://user-images.githubusercontent.com/36137133/51284369-920f5c80-19eb-11e9-9992-31f5b771342e.png)

**Comment by Su1phur** [comment]
Not enough info:
needs to see if other branches has been completed

**Comment by Su1phur** [comment]
wrong button

**Comment by Drowse** [comment]
Fixed Japan'a paths
