### ISSUE TITLE
Switzerland doesn't have some national spirit gfx

### ISSUE THREAD

**Issue by donbg** [jespertjee/FR#77]
![image](https://user-images.githubusercontent.com/40672374/51347794-ff2cfb80-1a98-11e9-9072-2a345a387aec.png)
Those are (from left to right)
- Continuing Economic Planning
- Hugo Coiti (localization prob missing as well)
- Treaty of Munich

will keep this updated if I find others

**Comment by Omanisch** [comment]
being redone
