### ISSUE TITLE
Switzerland events with no localization

### ISSUE THREAD

**Issue by donbg** [jespertjee/FR#78]
Following events have no description loc:
-swi.1
-swi.7
-swi.9

will comment below if I find others

**Comment by donbg** [comment]
swi.16

**Comment by donbg** [comment]
swi.20
swi.30

**Comment by donbg** [comment]
I think I have not seen an event for Switzerland that had description localization. So I'm pretty much gonna state here that all events don't have description loc

**Comment by Omanisch** [comment]
being redone
