### ISSUE TITLE
Switzerland National Focii without effects

### ISSUE THREAD

**Issue by donbg** [jespertjee/FR#79]
National focii that have no effects and still take time (35 days usually) to complete:

"Standup"
"Revise the Treaty"
"The Great War Refugee Policy"
"The Voralberg Question"

**Comment by donbg** [comment]
"SWI_status_quo_council_membership"
"CDVP becomes senior member"
"SWI_FDP_maintains_seniority"

**Comment by Omanisch** [comment]
being redone
