### ISSUE TITLE
Soviet Union Lenin's death is lackluster

### ISSUE THREAD

**Issue by donbg** [jespertjee/FR#87]
Lenin's death feels really lackluster atm. There's just one event with a small sentence talking about him dying.

I feel like his death should be a small chain of events with a buildup (Lenin collapses! or something like that) and a climax (Lenin passes away) and then some sort of "afterword" with a funeral ceremony for him which is attended by all of Moscow.

**Comment by fbruchmueller** [comment]
Good idea. Also gonna add some events afterwards that show how the union is basically in chaos

**Comment by fbruchmueller** [comment]
added some events. Shouldn't be the case now anymore hopefully
