### ISSUE TITLE
You can annex Insulindia without being forced to give it back.

### ISSUE THREAD

**Issue by fbruchmueller** [jespertjee/FR#9]
**Explanation of the issue:**
You can annex Insulindia without being forced to give it back resulting in bordergore.

**Screenshots / Video:**

https://cdn.discordapp.com/attachments/374254933089845249/526908035344629760/unknown.png

**Comment by Steffplays123** [comment]
Have this been solved yet, or should I do something about it?

**Comment by fbruchmueller** [comment]
This hasn't been solved yet. @SuperMarks pls fix
