### ISSUE TITLE
Default japanese name for fleets is FLEET_NAME

### ISSUE THREAD

**Issue by karrot1** [jespertjee/FR#91]
**Explanation of the issue:**
I mean, that's it.

**Steps to reproduce:**

1. Create a fleet

2. Take a look

**Possible cause:**
I assume FLEET_NAME is the default name if no-one provided real names.

**Screenshots / Video:**
![20190121122858_1](https://user-images.githubusercontent.com/6722625/51505031-49242300-1db2-11e9-9223-bb3214fd12ce.jpg)

**Comment by Drowse** [comment]
Seems to work for me
