### ISSUE TITLE
Japan's national spirits have weird names

### ISSUE THREAD

**Issue by karrot1** [jespertjee/FR#94]
**Explanation of the issue:**
The national spirits Japan gets have really weird names

**Steps to reproduce:**

1. Get a national spirit

2. Weird

**Screenshots / Video:**
![20190121130242_1](https://user-images.githubusercontent.com/6722625/51505219-4d9d0b80-1db3-11e9-9808-9b2ed89f9618.jpg)

**Comment by Su1phur** [comment]
old version - fixed
