### ISSUE TITLE
Democratic Japan can be locked out of its foreign policy trees

### ISSUE THREAD

**Issue by karrot1** [jespertjee/FR#95]
**Explanation of the issue:**
If the San Fran thing with the US goes badly and whatever is needed to make the UK ally Japan doesn't happen, Japan gets no foreign policy tree other than the one it shares with non-democratic japan

**Steps to reproduce:**

1. As Japan screw up the san fran thing

2. That's it

**Screenshots / Video:**
![20190121131159_1](https://user-images.githubusercontent.com/6722625/51505273-a53b7700-1db3-11e9-92e3-1e4058a77fc9.jpg)

**Comment by Drowse** [comment]
More of a design issue than bug. I did rework how both of those alliances work though so they should be easier to form
