### ISSUE TITLE
Japanese South Asia focus can never be taken

### ISSUE THREAD

**Issue by karrot1** [jespertjee/FR#96]
**Explanation of the issue:**
The focus requires two mutually exclusive focuses. Furthermore, it is at the end of two trees that are mutually exclusive if Japan goes Democratic, so even if the mutual exclusion thing were fixed, democratic Japan could never take it.

**Screenshots / Video:**
![20190121132249_1](https://user-images.githubusercontent.com/6722625/51505381-272ba000-1db4-11e9-8f4d-1733079b7dc0.jpg)

**Comment by Su1phur** [comment]
old version - fixed already
